// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsmjypunvehwiutowuxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbWp5cHVudmVod2l1dG93dXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NzgyMTgsImV4cCI6MjA1MzM1NDIxOH0.gTRiS7MLDUd1ye9J8osiOPleAcS6wO40YpbCGXnWyZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);